### PR TITLE
[WIP] Add varint unit tests

### PR DESCRIPTION
**Pull request by deathcap**
Adds some varint unit tests extracted from https://github.com/roblabla/ProtoDef/pull/51

This leaves the >32-bit overflow behavior (tests commented-out for now)

### CODE REVIEW

**Comment by rom1504** [comment]
I added all the passing tests in https://github.com/roblabla/ProtoDef/commit/29c04127e89ee51f39ca0e8deaa89bad375a9eaa

I'll let you add the rest of them ;)

**Comment by roblabla** [comment]
Please use it.skip instead of commenting out.

**Comment by rom1504** [comment]
Might need to add 2 things to my test schema for this:
* a skip property
* a "should fail" property

**Comment by rom1504** [comment]
seems like we haven't needed this
if someone need this one day, he can reopen

**Pull request closed without merging**
