### PR TITLE
Add Optional `skipChecks` to Disable Array Size Check

### PR DESCRIPTION
**Pull request by bdkopen**
Adds an optional `skipChecks` to disable a max array length check. The array length check was added to address [V8 crash concerns](https://github.com/PrismarineJS/prismarine-nbt/issues/85#issuecomment-1873448950), however this is not a concern for some use cases.

This implements the support necessary to address #150 and [#85](https://github.com/PrismarineJS/prismarine-nbt/issues/85). The prismarine-nbt PR that uses these changes can be found [here](https://github.com/PrismarineJS/prismarine-nbt/pull/91).

### CODE REVIEW

**Comment by extremeheat** [comment]
Can you open the PR for prismarine-nbt? You don't need to wait for a PR to be merged to use it in another PR if there is a chain ; simply set the dependency to point to a branch on github (`npm install user/repo#branch` will auto update package.json).

**Comment by rom1504** [comment]
This option should be added to docs

**Comment by bdkopen** [comment]
> Can you open the PR for prismarine-nbt? You don't need to wait for a PR to be merged to use it in another PR if there is a chain ; simply set the dependency to point to a branch on github (`npm install user/repo#branch` will auto update package.json).

[PR](https://github.com/PrismarineJS/prismarine-nbt/pull/91) is open. Let me know if I should approach anything differently.

> This option should be added to docs

Good idea! I added this to the docs and type definitions.

**Comment by rom1504** [comment]
Merging but I note this is missing a test. Would be great to add one to avoid regressions

**Pull request merged**
